omero_mapr/tree.py, setup.py
This fixes autocomplete search that will results in returning first results matching value% (starting from the given phrase) then everything that match %value% (contains given phrase)
To test check:
first results matching value% will be sorted by lenght, rest of the results matching %value% will be sorted alphabetical 
cc: @pwalczysko
=> autocomplete should return first results matching value%

omero_mapr/tree.py
this fixes Illegal query reported in https://docs.google.com/spreadsheets/d/1uPbSD4NtwEiH3S6-ijsARDLGg--816LExE4BByMH0Cc/edit#gid=385968527
test for example http://ebi-embassy-cherry.openmicroscopy.org/mapr/gene/?value=NUP107
=> fix missing coma in a query

omero_mapr/__init__.py, omero_mapr/static/mapr/css/ome.mapr.css, omero_mapr/static/mapr/javascript/ome.mapr.js, omero_mapr/static/mapr/javascript/ome.mapr.ui.autocomplete.js, omero_mapr/templates/mapr/base_mapr.html, omero_mapr/testlib/__init__.py, omero_mapr/tree.py, omero_mapr/views.py, tests/conftest.py, tests/integration/bulk_to_map_annotation_context_ns.csv, tests/integration/test_config.py, tests/integration/test_mapr.py, tests/integration/test_mapr_autocomplete.py, tests/integration/test_mapr_views.py
This PR relaxe queries to load case insensitive data https://trello.com/c/M3q00BhI/55-mapr-case-insensitive-searching
Test:
- **Case sensitive is only enabled in gene and compound tab** (configurable)
- Check:
- mapr/gene/?value=cdc14
- mapr/gene/?value=cdc14&case_sensitive=true
- mapr/gene/?value=cdc14&case_sensitive=true&query=true
**`case_sensitive` & `query` are not mutually exclusive**
- type `cdc14` in autocomplete and test `Match case`
- check if tests passes https://idr-ci.openmicroscopy.org:8443/job/MAPR-test/
- check help tooltip in `?` button
=> load case insensitive data to the tree

README.rst
See https://trello.com/c/2bBx96kX/23-mapr-installation
Make the install docs more user-friendly with some background info and example how to set-up Map Annotations to work with a given config.
Staged at https://github.com/will-moore/omero-mapr/tree/README_more_info
TODO: I'll also look at using ```mapr``` to search for client-created Map Annotations as suggested elsewhere...
=> Add more info and example config to README

omero_mapr/__init__.py, requirements.txt
The 4.9.0 release of django-redis drops support for versions of Django below 1.11.
See also https://github.com/openmicroscopy/openmicroscopy/pull/5674.
As the version of `omero-mapr` currently break the https://github.com/openmicroscopy/ansible-role-omero-web-apps role in https://github.com/IDR/deployment, propose to cut the `0.2.1` release of `omero-mapr 0.2.1` and bump in IDR - see  https://github.com/ome/omero-mapr/milestone/16 and https://github.com/ome/omero-mapr/milestone/17.
=> Cap django-redis prior to 4.9.0

setup.py
The pytest-runner is already declared in requirements-test.txt. This change should fix the installation of omero-mapr on old Python/pip (e.g. CentOS) following the PyPI TLS v1.0/1.1 deprecation
See also https://github.com/openmicroscopy/omero-marshal/pull/50
To test this PR,
- check Travis remains green
- test
```
$ docker run --rm -it centos:centos7
[root@985cea0418f9 /]# yum install -y python-virtualenv && virtualenv /tmp/venv
[root@985cea0418f9 /]# /tmp/venv/bin/pip install omero-mapr # should fail
[root@985cea0418f9 /]# /tmp/venv/bin/pip install https://github.com/sbesson/omero-mapr/archive/pypi_tls_1.0.zip # should work
```
=> Remove setup_requires declaration from setup.py

omero_mapr/static/mapr/css/ome.mapr.css
Fixes style broken in
https://github.com/openmicroscopy/openmicroscopy/pull/5669
Before and after this fix:
In general we should try not to reuse css from webclient in different components in other apps, since this is quite fragile. However, it's tricky to know what is likely to break and we don't want to duplicate all of webclient css!
=> filtersearch css fix

README.rst
Adding the ```any:[]``` config to the docs.
This is what we are demo'ing at the OME meeting metadata workshop and is also found in the idr mapr config (see https://github.com/openmicroscopy/prod-playbooks/pull/67#issuecomment-392089315).
Page staged at https://github.com/will-moore/omero-mapr/tree/add_anyvalue_config_to_README
=> Add AnyValue config to README

omero_mapr/urls.py, omero_mapr/views.py
This makes the mapr_settings.CONFIG available as JSON data, so it can be used by other apps.
E.g. https://github.com/ome/omero-gallery/pull/25/
To test:
- go to ```/mapr/api/config/``` E.g. http://web-dev-merge.openmicroscopy.org/mapr/api/config/
- Should see JSON that corresponds to ```omero.web.mapr.config``` setting.
=> Add /api/config/ to return mapr_settings.CONFIG as JSON

omero_mapr/static/mapr/javascript/ome.mapr.js, omero_mapr/templates/mapr/base_mapr.html, omero_mapr/views.py
This adds support for the URL e.g. ```?show=screen-2``` so that we can link to a Study *within* a Gene etc.
This may be a useful entry point if we use a different UI / App to do the initial mapr query, then we want to link to a particular study within a matching term in the mapr app.
E.g. http://web-dev-merge.openmicroscopy.org/mapr/gene/?value=CDK5RAP2&show=project-4501 (user-3)
In mapr, this will load Genes that match value ```CDK5RAP2```. With the 'show' query, we load the top level gene nodes of the tree, to check their "study" children for a match with the 'show' query. If we find a match then this node is selected and expanded.
NB: This is a different approach from the ```webclient/?show=image-2``` where the node may be deep in the tree and needs us to load the "path" to this node …
=> Support ?show=screen-123 for mapr jstree

omero_mapr/static/mapr/javascript/ome.mapr.js
Fixes bug reported by @jrswedlow 
To test try e.g.
http://web-dev-merge.openmicroscopy.org/mapr/gene/?value=Kif2C%20(AB)&show=plate-4401
This should find the plate in the jsTree and select it.
=> Fix show when value has whitespace

omero_mapr/templates/webclient/data/includes/right_plugin.general.js.html
See https://www.openmicroscopy.org/qa2/qa/feedback/27241/. 
To test, with MAPR installed, search for a Well by ID and click on the Well in search results.
The Well (index=0) should load in the right panel.
NB: This took me a while to track down as I'd forgotten that I had MAPR installed locally so when I tried editing my local ```right_plugin.general.js.html``` I saw no changes, and the local code already had the bug fixed. Need to remember that any changes made to this file in ```openmicroscopy``` have to be duplicated in ```mapr```.
=> well index fix metadata general

omero_mapr/static/mapr/javascript/ome.mapr.ui.autocomplete.js
Noticed while comparing URLs with those from IDR gallery.
Previously URLs to load auto-complete data looked like e.g.
```
http://localhost:4080/mapr/api/autocomplete/gene/?... ..experimenter_id%5Bid%5D=-1&experimenter_id%5BfullName%5D=
```
since the whole ```WEBCLIENT.active_user``` object was being serialised to the query.
With this fix, it should now look like ```experimenter_id=-1``` (inspect XHR requests in devtools).
To test:
- Go to mapr, e.g. https://merge-ci.openmicroscopy.org/web/mapr/anyvalue/
- Open devtools in your browser, click on Network tab and XHR.
- Start typing in the mapr search input (above the tree). It doesn't matter too much what you type but it will look for 'any' matching Values from map annotations.
- You should see requests in the network tab that have …
=> Use active_user.id instead of object in autocomplete REST data

README.rst, omero_mapr/mapr_settings.py, omero_mapr/templates/webclient/data/includes/right_plugin.general.js.html, omero_mapr/tree.py
Deployed on the idr0094 server
A mapr key of the form `xxx URL` is now only matched with a preceding row with key `xxx`. This is a change to the previous behaviour where all(?) rows were searched for a matching substring value.
Closes https://github.com/ome/omero-mapr/issues/62
=> Mapr value icon: match with previous row

omero_mapr/tree.py, requirements.txt
This fixes a breaking change from https://github.com/ome/omero-web/pull/329
where `omeroweb.webclient.tree._marshal_image()` expects a row with 4 values (`sizeT` was added in PR above).
To test:
- Search in mapr tab. e.g for Gene.
- Browse Project / Dataset and expand to load Images
- Images should load instead of error:
cc @sbesson @francesw - We need to get this included in next IDR release (which includes omero-web PR above).
=> Include sizeT in _marshal_image() row

omero_mapr/static/mapr/css/ome.mapr.css
Fixes #75
To test on merge-ci: click on 'Genes' link an type in mapr search - Auto-complete issue at https://github.com/ome/omero-web/pull/433#issuecomment-1396774881 should be fixed.
=> Fix auto-complete css for omero-web 5.18.0 jquery-ui 1.13.2

.github/workflows/omero_plugin.yml, .github/workflows/publish_pypi.yml
Bump action versions to avoid deprecation warning cf. https://github.com/ome/omero-mapr/actions/runs/4374470793
=> Upgrade action

.omeroci/app-deps, omero_mapr/testlib/__init__.py, requirements-test.txt
With the new release of omero-metadata (0.13.0), ``omero.util`` can be replaced by ``omero-metadata``
=> Replace omero utils

omero_mapr/views.py
Fixes return of default favicon if one is not loaded from domain.
cc @francesw 
To test, go to e.g. /mapr/favicon/?u=https%3A%2F%2Flod.humanatlas.io%2Fomap%2F18-lymph-node-cell-dive-ibex%2Fv1.0%2F and you should see a tiny globe icon shown on the page.
=> fix return of default favicon if not found

CHANGELOG.md
@francesw @jburel I'll get this released and bumped in IDR along with gallery if no objections?
=> changelog 0.5.3
